### ISSUE TITLE
can't install on my another pc's chrome

### ISSUE THREAD

**Issue by neelpopat** [dnut/AdBlock-Pure#4]
hi i can't install adblock pure  on my another pc's chrome as i cannot find it on chrome store now. So can you help me with this how can i install it ?

**Comment by dnut** [comment]
Google is one of the contributing parties involved in the "acceptable ads" scam, so they oppose projects like AdBlock Pure. Likewise, they have removed it from the Web Store. To use AdBlock Pure, you would have to follow the instructions in the readme.
